### ISSUE TITLE
Enhancement: Field custom actions

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#824]
Allow custom actions to be linked to fields. This functionality works like custom actions/scripts, but it is triggered from a field. 

Use case: allow users to create scripts to provide the field value. For example, use a script that calls your LLM to generate content.

## Tasks

- [x] Update the [@frontmatter/extensibility](https://www.npmjs.com/package/@frontmatter/extensibility) dependency
- [x] Integrate in the following field types:
	- [x] Text field
	- [x] Taxonomy field
	- [x] Single image field
	- [x] Multiple images field
- [x] Documentation
	- [x] Fields documentation
	- [x] Extensibility documentation
- [x] Schema generation + add scripts reference
- [x] Examples

**Comment by estruyf** [comment]
Released in version v10.3.0.
